import us

FIPS_TO_ABBR = us.states.mapping("fips", "abbr")

COURT_LOOKUP_SHORT = {
    "AL": "ala",
    "AK": "alaska",
    "AZ": "ariz",
    "AR": "ark",
    "CA": "cal",
    "CO": "colo",
    "CT": "conn",
    "DE": "del",
    "FL": "fla",
    "GA": "ga",
    "HI": "haw",
    "ID": "idaho",
    "IL": "ill",
    "IN": "ind",
    "IA": "iowa",
    "KS": "kan",
    "KY": "ky",
    "LA": "la",
    "ME": "me",
    "MD": "md",
    "MA": "mass",
    "MI": "mich",
    "MN": "minn",
    "MS": "miss",
    "MO": "mo",
    "MT": "mont",
    "NE": "neb",
    "NV": "nev",
    "NH": "nh",
    "NJ": "nj",
    "NM": "nm",
    "NY": "ny",
    "NC": "nc",
    "ND": "nd",
    "OH": "ohio",
    "OK": "okla",
    "OR": "or",
    "PA": "pa",
    "RI": "ri",
    "SC": "sc",
    "SD": "sd",
    "TN": "tenn",
    "TX": "tex",
    "UT": "utah",
    "VT": "vt",
    "VA": "va",
    "WA": "wash",
    "WV": "wva",
    "WI": "wis",
    "WY": "wyo",
}
COURT_LOOKUP_LONG = {
    "Alabama": "ala",
    "Alaska": "alaska",
    "Arizona": "ariz",
    "Arkansas": "ark",
    "California": "cal",
    "Colorado": "colo",
    "Connecticut": "conn",
    "Delaware": "del",
    "Florida": "fla",
    "Georgia": "ga",
    "Hawaii": "haw",
    "Idaho": "idaho",
    "Illinois": "ill",
    "Indiana": "ind",
    "Iowa": "iowa",
    "Kansas": "kan",
    "Kentucky": "ky",
    "Louisiana": "la",
    "Maine": "me",
    "Maryland": "md",
    "Massachusetts": "mass",
    "Michigan": "mich",
    "Minnesota": "minn",
    "Mississippi": "miss",
    "Missouri": "mo",
    "Montana": "mont",
    "Nebraska": "neb",
    "Nevada": "nev",
    "New Hampshire": "nh",
    "New Jersey": "nj",
    "New Mexico": "nm",
    "New York": "ny",
    "North Carolina": "nc",
    "North Dakota": "nd",
    "Ohio": "ohio",
    "Oklahoma": "okla",
    "Oregon": "or",
    "Pennsylvania": "pa",
    "Rhode Island": "ri",
    "South Carolina": "sc",
    "South Dakota": "sd",
    "Tennessee": "tenn",
    "Texas": "tex",
    "Utah": "utah",
    "Vermont": "vt",
    "Virginia": "va",
    "Washington": "wash",
    "West Virginia": "wva",
    "Wisconsin": "wis",
    "Wyoming": "wyo",
}
