# Generated by Django 5.2.14 on 2026-05-23 23:45

import datetime
import django.db.models.deletion
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=datetime.date.today)),
                ('prompt_start', models.TextField(blank=True, null=True)),
                ('model_id', models.CharField(default='gemini-2.5-flash')),
                ('skips', models.TextField(null=True)),
                ('avg_case_query_time', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.CharField(unique=True)),
                ('name', models.CharField()),
                ('court_level', models.CharField(choices=[('sup', 'Supreme Court'), ('apl', 'Appellate Court'), ('lwr', 'Lower Court')], null=True)),
                ('court_type', models.CharField()),
                ('bench_size', models.IntegerField(blank=True, null=True)),
                ('selection_type', models.CharField(choices=[('partisan election', 'Partisan'), ('nonpartisan election', 'Nonpartisan'), ('appointment', 'Appointment'), ('retention election', 'Retention'), ('elected by legislature', 'Legislature')])),
                ('selection_method', models.TextField(blank=True)),
                ('selection_jurisdiction', models.CharField(blank=True, choices=[('statewide', 'Statewide'), ('district', 'District'), ('circuit', 'Circuit')])),
                ('term_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('initial_term_length', models.TextField(blank=True)),
                ('retention_method', models.TextField(blank=True)),
                ('subsequent_term_length', models.TextField(blank=True)),
                ('interim_selection_method', models.TextField(blank=True)),
                ('interim_term_length', models.TextField(blank=True)),
                ('chief_justice_selection_method', models.TextField(blank=True)),
                ('chief_justice_term_length', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('constitutional_reference', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_canonical', models.CharField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], null=True)),
                ('race', models.CharField(blank=True, choices=[('white', 'White'), ('black or african american', 'Black'), ('american indian or alaska native', 'Amin'), ('asian', 'Asian'), ('native hawaiian or other pacific islander', 'Nhpi'), ('other', 'Other')], null=True)),
                ('party_registration', models.CharField(blank=True, choices=[('republican', 'Rep'), ('democrat', 'Dem'), ('independent', 'Ind'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown')),
                ('professional_experience', models.TextField(blank=True)),
                ('law_school', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountyToCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('county', models.CharField()),
                ('fips', models.CharField()),
                ('court', models.ManyToManyField(to='judgement_call.court')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(null=True)),
                ('docket_no', models.CharField()),
                ('case_type', models.CharField(blank=True, choices=[('Civil Rights', 'Civil Rights'), ('Government Structure', 'Gov Structure'), ('Economic and Labor Rights', 'Econ Labor'), ('Voting Rights and Elections', 'Voting Elections'), ('Criminal Law', 'Criminal Law'), ('Environment', 'Environment'), ('Judicial Selection and Administration', 'Judicial Selection'), ('Education', 'Education'), ('Speech and Religion', 'Speech Religion'), ('Civil Due Process', 'Due Process'), ('Reproductive Rights', 'Reproductive Rights'), ('Torts and Liability', 'Torts'), ('Judicial Interpretation', 'Judicial Interpretation'), ('Election 2024', 'Election2024')], null=True)),
                ('case_title', models.CharField()),
                ('description', models.TextField()),
                ('decision_status', models.BooleanField(default=True)),
                ('decision_outcome', models.CharField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_winner', models.CharField(blank=True, choices=[('plaintiff', 'Plaintiff'), ('defendant', 'Defendant'), ('other', 'Other')], null=True)),
                ('plaintiff_argument', models.TextField(blank=True, null=True)),
                ('defendant_argument', models.TextField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('consumers', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('reproductive_rights', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('democratic_norms', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('free_press', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('public_health', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('separation_church_state', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('voting_access', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('public_education', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('free_speech', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('privacy', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('worker_rights', models.CharField(blank=True, choices=[('protected', 'Protected'), ('infringed', 'Infringed'), ('NA', 'Na')])),
                ('document_url', models.URLField(blank=True, null=True)),
                ('case_processing_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='judgement_call.caseprocessingrun')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='judgement_call.court')),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='judgement_call.court')),
            ],
            options={
                'verbose_name_plural': 'Aliases',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(blank=True, unique=True)),
                ('election_date', models.DateField()),
                ('filing_deadline', models.DateField(null=True)),
                ('election_type', models.CharField(choices=[('partisan election', 'Partisan'), ('nonpartisan election', 'Nonpartisan'), ('retention election', 'Retention')], null=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='judgement_call.court')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ruling', models.CharField(choices=[('concur', 'Concur'), ('dissent', 'Dissent'), ('other', 'Other')])),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgement_call.case')),
                ('judge_alias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='judgement_call.alias')),
            ],
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgement_call.election')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgement_call.person')),
            ],
            options={
                'verbose_name_plural': 'Candidacies',
            },
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('selection_type', models.CharField(choices=[('partisan election', 'Partisan'), ('nonpartisan election', 'Nonpartisan'), ('appointment', 'Appointment'), ('retention election', 'Retention'), ('elected by legislature', 'Legislature')])),
                ('ticket_party', models.CharField(blank=True, choices=[('republican', 'Rep'), ('democrat', 'Dem'), ('independent', 'Ind'), ('other', 'Other'), ('unknown', 'Unknown')])),
                ('appointer_name', models.CharField(blank=True)),
                ('appointer_party', models.CharField(blank=True, choices=[('republican', 'Rep'), ('democrat', 'Dem'), ('independent', 'Ind'), ('other', 'Other'), ('unknown', 'Unknown')])),
                ('chief_justice', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='judgement_call.court')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judgement_call.person')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='incumbent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judgement_call.tenure'),
        ),
        migrations.AddField(
            model_name='alias',
            name='tenure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='judgement_call.tenure'),
        ),
    ]
