# Generated by Django 5.2 on 2026-04-28 19:45

import django.db.models.deletion
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("court_id", models.CharField()),
                ("name", models.CharField()),
                ("state", localflavor.us.models.USStateField(max_length=2)),
                (
                    "court_level",
                    models.CharField(
                        choices=[
                            ("sup", "Supreme Court"),
                            ("apl", "Appellate Court"),
                            ("lwr", "Lower Court"),
                        ],
                        null=True,
                    ),
                ),
                ("court_type", models.CharField()),
                ("bench_size", models.IntegerField(blank=True, null=True)),
                (
                    "selection_type",
                    models.CharField(
                        choices=[
                            ("partisan election", "Partisan"),
                            ("nonpartisan election", "Nonpartisan"),
                            ("appointment", "Appointment"),
                        ]
                    ),
                ),
                ("selection_method", models.TextField(blank=True)),
                (
                    "selection_jurisdiction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("statewide", "Statewide"),
                            ("district", "District"),
                            ("circuit", "Circuit"),
                        ],
                    ),
                ),
                ("term_length", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name_canonical", models.TextField()),
                ("name_alias", models.TextField()),
                ("birth_date", models.DateField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("M", "Male"), ("F", "Female"), ("O", "Other")]
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("White", "White"),
                            ("Black or African American", "Black"),
                            ("American Indian or Alaska Native", "Amin"),
                            ("Asian", "Asian"),
                            ("Native Hawaiian or Other Pacific Islander", "Nhpi"),
                            ("Other", "Other"),
                        ],
                    ),
                ),
                (
                    "party_registration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Republican", "Rep"),
                            ("Democrat", "Dem"),
                            ("Independent", "Ind"),
                            ("Other", "Other"),
                        ],
                    ),
                ),
                ("professional_experience", models.TextField(blank=True)),
                ("law_school", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CountyToCourt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("state", localflavor.us.models.USStateField(max_length=2)),
                ("county", models.CharField()),
                ("fips", models.CharField()),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judgement_call.court"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("docket_no", models.TextField()),
                (
                    "case_type",
                    models.CharField(choices=[("criminal", "Criminal"), ("civil", "Civil")]),
                ),
                ("case_title", models.CharField()),
                ("description", models.TextField()),
                ("subject_matter", models.CharField()),
                ("pro_con", models.CharField()),
                ("decision_status", models.BooleanField()),
                ("decision_outcome", models.CharField(blank=True, null=True)),
                ("decision_date", models.DateField(blank=True, null=True)),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="judgement_call.court"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="judgement_call.court"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judgement_call.election"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judgement_call.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tenure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True)),
                (
                    "selection_type",
                    models.CharField(
                        choices=[
                            ("partisan election", "Partisan"),
                            ("nonpartisan election", "Nonpartisan"),
                            ("appointment", "Appointment"),
                        ]
                    ),
                ),
                (
                    "ticket_party",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Republican", "Rep"),
                            ("Democrat", "Dem"),
                            ("Independent", "Ind"),
                            ("Other", "Other"),
                        ],
                    ),
                ),
                ("appointer_name", models.CharField(blank=True)),
                (
                    "appointer_party",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Republican", "Rep"),
                            ("Democrat", "Dem"),
                            ("Independent", "Ind"),
                            ("Other", "Other"),
                        ],
                    ),
                ),
                ("chief_justice", models.BooleanField(default=False)),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="judgement_call.court"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judgement_call.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndividualOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "ruling",
                    models.CharField(
                        choices=[("concur", "Concur"), ("dissent", "Dissent"), ("other", "Other")]
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judgement_call.case"
                    ),
                ),
                (
                    "tenure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judgement_call.tenure"
                    ),
                ),
            ],
        ),
    ]
