# Generated by Django 5.2 on 2026-04-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name_alias",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="person",
            name="name_canonical",
            field=models.CharField(),
        ),
    ]
