# Generated by Django 5.2.14 on 2026-05-23 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgement_call', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='document_url',
        ),
        migrations.RemoveField(
            model_name='election',
            name='election_id',
        ),
        migrations.RemoveField(
            model_name='election',
            name='filing_deadline',
        ),
        migrations.AlterField(
            model_name='court',
            name='court_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='incumbent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='judgement_call.tenure'),
        ),
    ]
