# Generated by Django 5.2 on 2026-04-29 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0002_alter_person_name_alias_alter_person_name_canonical"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="court",
            name="state",
        ),
    ]
