# Generated by Django 5.2 on 2026-05-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0003_remove_court_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidacy",
            options={"verbose_name_plural": "Candidacies"},
        ),
        migrations.RemoveField(
            model_name="case",
            name="pro_con",
        ),
        migrations.RemoveField(
            model_name="case",
            name="subject_matter",
        ),
        migrations.RemoveField(
            model_name="individualopinion",
            name="tenure",
        ),
        migrations.AddField(
            model_name="case",
            name="consumers",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="decision_winner",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plaintiff", "Plaintiff"),
                    ("defendant", "Defendant"),
                    ("other", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="defendant_argument",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="democratic_norms",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="free_press",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="free_speech",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="plaintiff_argument",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="privacy",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="public_education",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="public_health",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="reproductive_rights",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="separation_church_state",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="voting_access",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="worker_rights",
            field=models.CharField(
                blank=True,
                choices=[("protected", "Protected"), ("infringed", "Infringed"), ("NA", "Na")],
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Civil Rights", "Civil Rights"),
                    ("Government Structure", "Gov Structure"),
                    ("Economic and Labor Rights", "Econ Labor"),
                    ("Voting Rights and Elections", "Voting Elections"),
                    ("Criminal Law", "Criminal Law"),
                    ("Environment", "Environment"),
                    ("Judicial Selection and Administration", "Judicial Selection"),
                    ("Education", "Education"),
                    ("Speech and Religion", "Speech Religion"),
                    ("Civil Due Process", "Due Process"),
                    ("Reproductive Rights", "Reproductive Rights"),
                    ("Torts and Liability", "Torts"),
                    ("Judicial Interpretation", "Judicial Interpretation"),
                    ("Election 2024", "Election2024"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="decision_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="docket_no",
            field=models.CharField(),
        ),
        migrations.RemoveField(
            model_name="countytocourt",
            name="court",
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("alias", models.CharField()),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="judgement_call.court"
                    ),
                ),
                (
                    "tenure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="judgement_call.tenure",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Aliases",
            },
        ),
        migrations.AddField(
            model_name="individualopinion",
            name="judge_alias",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="judgement_call.alias"
            ),
        ),
        migrations.AddField(
            model_name="countytocourt",
            name="court",
            field=models.ManyToManyField(to="judgement_call.court"),
        ),
    ]
