# Generated by Django 5.2 on 2026-05-01 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0004_alter_candidacy_options_remove_case_pro_con_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="name_alias",
        ),
    ]
