# Generated by Django 5.2.13 on 2026-05-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0005_remove_person_name_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_id",
            field=models.CharField(null=True),
        ),
    ]
