# Generated by Django 5.2.13 on 2026-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0006_case_case_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="selection_type",
            field=models.CharField(
                choices=[
                    ("partisan election", "Partisan"),
                    ("nonpartisan election", "Nonpartisan"),
                    ("appointment", "Appointment"),
                    ("retention election", "Retention"),
                    ("elected by legislature", "Legislature"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("m", "Male"), ("f", "Female"), ("o", "Other")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="party_registration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("republican", "Rep"),
                    ("democrat", "Dem"),
                    ("independent", "Ind"),
                    ("other", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("white", "White"),
                    ("black or african american", "Black"),
                    ("american indian or alaska native", "Amin"),
                    ("asian", "Asian"),
                    ("native hawaiian or other pacific islander", "Nhpi"),
                    ("other", "Other"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenure",
            name="appointer_party",
            field=models.CharField(
                blank=True,
                choices=[
                    ("republican", "Rep"),
                    ("democrat", "Dem"),
                    ("independent", "Ind"),
                    ("other", "Other"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tenure",
            name="selection_type",
            field=models.CharField(
                choices=[
                    ("partisan election", "Partisan"),
                    ("nonpartisan election", "Nonpartisan"),
                    ("appointment", "Appointment"),
                    ("retention election", "Retention"),
                    ("elected by legislature", "Legislature"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tenure",
            name="ticket_party",
            field=models.CharField(
                blank=True,
                choices=[
                    ("republican", "Rep"),
                    ("democrat", "Dem"),
                    ("independent", "Ind"),
                    ("other", "Other"),
                ],
            ),
        ),
    ]
