# Generated by Django 5.2.13 on 2026-05-12 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0007_alter_court_selection_type_alter_person_birth_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="election",
            old_name="date",
            new_name="election_date",
        ),
        migrations.AddField(
            model_name="election",
            name="incumbent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="judgement_call.tenure",
            ),
        ),
    ]
