# Generated by Django 5.2.13 on 2026-05-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0008_rename_date_election_election_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="chief_justice_selection_method",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="court",
            name="chief_justice_term_length",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="court",
            name="constitutional_reference",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="court",
            name="initial_term_length",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="court",
            name="interim_selection_method",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="court",
            name="interim_term_length",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="court",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="court",
            name="qualifications",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="court",
            name="retention_method",
            field=models.CharField(
                choices=[
                    ("partisan election", "Partisan"),
                    ("nonpartisan election", "Nonpartisan"),
                    ("appointment", "Appointment"),
                    ("retention election", "Retention"),
                    ("elected by legislature", "Legislature"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="subsequent_term_length",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="election",
            name="election_type",
            field=models.CharField(
                choices=[
                    ("partisan election", "Partisan"),
                    ("nonpartisan election", "Nonpartisan"),
                    ("retention election", "Retention"),
                ],
                null=True,
            ),
        ),
    ]
