# Generated by Django 5.2.13 on 2026-05-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0009_court_chief_justice_selection_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="retention_method",
            field=models.TextField(blank=True, default="unknown"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="party_registration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("republican", "Rep"),
                    ("democrat", "Dem"),
                    ("independent", "Ind"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
            ),
        ),
        migrations.AlterField(
            model_name="tenure",
            name="appointer_party",
            field=models.CharField(
                blank=True,
                choices=[
                    ("republican", "Rep"),
                    ("democrat", "Dem"),
                    ("independent", "Ind"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tenure",
            name="ticket_party",
            field=models.CharField(
                blank=True,
                choices=[
                    ("republican", "Rep"),
                    ("democrat", "Dem"),
                    ("independent", "Ind"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
            ),
        ),
    ]
