# Generated by Django 5.2.13 on 2026-05-20 21:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0010_alter_court_retention_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseProcessingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateField(default=datetime.date.today)),
                ("prompt_start", models.TextField(blank=True, null=True)),
                ("model_id", models.CharField(default="gemini-2.5-flash")),
                ("skips", models.TextField(null=True)),
                ("avg_case_query_time", models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="tenure",
            name="scraped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenure",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenure",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="case_processing_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="judgement_call.caseprocessingrun",
            ),
        ),
    ]
