# Generated by Django 5.2.14 on 2026-05-23 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0011_caseprocessingrun_tenure_scraped_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="incumbent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="judgement_call.tenure",
            ),
        ),
    ]
