# Generated by Django 5.2.14 on 2026-05-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0012_alter_election_incumbent"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="document_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
