# Generated by Django 5.2.14 on 2026-05-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judgement_call", "0013_case_document_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="election_id",
            field=models.CharField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="election",
            name="filing_deadline",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="court",
            name="court_id",
            field=models.CharField(unique=True),
        ),
    ]
